### PR TITLE
Allow skipping the header on write

### PR DESCRIPTION
**Pull request by SquareByte**

### CODE REVIEW

**Comment by Ajnasz** [comment]
Hi @SquareByte 

What about setting it as a configuration parameter? I can imagine it to be a function which returns a string so it's easy to keep backward compatibility by setting the current implementation as default, also you can customize if needed but also easy  to disable it by returning an empty string.

**Comment by SquareByte** [comment]
@Ajnasz Yeah. While out of scope for my simple needs, I did think about allowing a custom string to print as a header. A callback is even more powerful. But I didn't want the complications that quickly arise from that:
 - What should arguments to the callback be? Just `this` (the IniReader instance)?
 - Do we handle the configurable newline explicitly, or leave it to the user to get it right?
 - Is the result of the callback assumed to be a comment and checked accordingly (each line starting with `';'` or `'#'`), or is anything allowed?
 - Tests ...

**Comment by Ajnasz** [comment]
>     * What should arguments to the callback be? Just `this` (the IniReader instance)?

Based on the [current usage](https://github.com/Ajnasz/IniReader/blob/master/lib/inireadercore.js#L647-L650) I would pass only the `le` variable, and in the [constructor](https://github.com/Ajnasz/IniReader/blob/master/lib/inireadercore.js#L252-L270) I would [bind the function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to `this`.

>     * Do we handle the configurable newline explicitly, or leave it to the user to get it right?

Pass it as an argument as we already pass it to other functions. If user doesn't use it, it's ok.

>     * Is the result of the callback assumed to be a comment and checked accordingly (each line starting with `';'` or `'#'`), or is anything allowed?

I would go for the minimal implementation and just append it to the output. To be honest, from my point of view this is a pretty useless part of the lib, so if I would write the lib now, I wouldn't add it :). I expect no real usages, but even if something come up we can still improve it. :) The important is the backward compatibility, so if no custom function configured return the same what we have now.

>     * Tests ...

Two test cases need I think, one for the default value and one for the custom configuration.

**Comment by SquareByte** [comment]
Ah, sorry, only now I see what you mean by passing as a configuration parameter. There is this hook system, I wasn't even aware of! I'll investigate how to rewrite my changes with that in mind ...

**Comment by SquareByte** [comment]
Reworked to be a new config function property `cfg.header` called on write().

I'm not sure about the tests though. I added a new "section" where I just call the existing function `testFileReadWrite` with 3 different header configs. Is this good enough?

**Comment by Ajnasz** [comment]
> Reworked to be a new config function property `cfg.header` called on write().
> 
> I'm not sure about the tests though. I added a new "section" where I just call the existing function `testFileReadWrite` with 3 different header configs. Is this good enough?

Hi @SquareByte 

Thank you for the changes!

The code looks good, I would add one change to tests. Currently we don't test what has been written as the header. The function  `testFileReadWrite` tests we can read the config what we wrote to the file.
Instead of calling this function, I recommend to test the actual file on the disk with a minimal config. Something like this:

```javascript
    // Test custom header
    (function () {
      const reader = new inireader.IniReader({
        header: function (le) {
        return "; TEST!" + le;
      }});
      reader.param('a.foo', 1);
      const fn = getRandomFilename();
      reader.write(fn);

      const content =  fs.readFileSync(fn);
      const str = content.toString('utf8');

      assert.equal(str, '; TEST!\n\n[a]\nfoo=1\n');
      fs.unlink(fn, function (err) { if (err) { throw err; } });
    }());
```

Also thanks for the grammar fixes :)

**Comment by SquareByte** [comment]
> The function testFileReadWrite tests if we can read the config what we wrote to the file

yeah, that was basically what I wanted. I did not care about the header, but only that the output is not "messed up".

I'll add explicit tests along what you outlined.

**Comment by SquareByte** [comment]
Test extension done.

**Review by Ajnasz — APPROVED** [review]

**Comment by Ajnasz** [comment]
Looking good! Thanks.

Could you squash the commits into one commit, please? Then I'll merge it and publish.

**Comment by SquareByte** [comment]
Isn't that something you do during the merge? I'm not sure, I'm not too familiar with that aspect of github.

Do I squash-merge into my forked master branch and make another pull-request from there? Could you help me with that?

**Comment by Ajnasz** [comment]
Yes, but then I will be the author of the commit (as far as I remember) and I don't want to take it from you. Besides that you can add a meaningful commit message which describes why the change has been created.
You can do it by `git rebase -i`

Here is short video about how to do it:

https://user-images.githubusercontent.com/38329/225303360-7a00ca88-e3cc-477f-84e0-e0b666818f01.mp4

***

But for me it's OK to do it myself, if it's good for you.

**Comment by SquareByte** [comment]
Yes, please. If you are fine with it, become the author. I don't want any ownership or copyright. I just need the functionality :)

**Pull request merged**
